version: '3.7'

services:

  sample-ui:
    container_name: sample-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:80'
    # environment:
    #   - NODE_ENV=development
    #   - CHOKIDAR_USEPOLLING=true
